# Generated by Django 4.0.1 on 2022-02-12 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вопроса')),
                ('text', models.TextField(verbose_name='Текст')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_post', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_article', models.TextField(verbose_name='Текст')),
                ('time_article', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('auth_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_article', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='anon.post', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комент',
                'verbose_name_plural': 'Коменты',
            },
        ),
    ]
