# Generated by Django 4.0.1 on 2022-02-14 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_article',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='auth_article',
            field=models.TextField(max_length=255, unique=True, verbose_name='Вопрос'),
        ),
    ]
