# Generated by Django 4.0.1 on 2022-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0002_article_likes_article_alter_article_auth_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auth_article',
            field=models.TextField(max_length=255, verbose_name='Вопрос'),
        ),
    ]
